# Generated by Django 5.2.8 on 2025-11-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_men', models.AutoField(db_column='id_men', primary_key=True, serialize=False)),
                ('asunto', models.CharField(blank=True, db_column='asunto', max_length=100, null=True)),
                ('cuerpo', models.TextField(blank=True, db_column='cuerpo', null=True)),
                ('fch_envio', models.DateTimeField(auto_now_add=True, db_column='fch_envio')),
                ('leido', models.BooleanField(db_column='leido', default=False)),
                ('id_destinatario', models.ForeignKey(db_column='id_destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='accounts.registro')),
                ('id_remitente', models.ForeignKey(db_column='id_remitente', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='accounts.registro')),
            ],
            options={
                'db_table': 'mensaje',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notif', models.AutoField(db_column='id_notif', primary_key=True, serialize=False)),
                ('tit_notif', models.CharField(db_column='tit_notif', max_length=100)),
                ('men_notif', models.TextField(db_column='men_notif')),
                ('fch_envio', models.DateTimeField(auto_now_add=True, db_column='fch_envio')),
                ('leida', models.BooleanField(db_column='leida', default=False)),
                ('id_usu', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, to='accounts.registro')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_rep', models.AutoField(db_column='id_rep', primary_key=True, serialize=False)),
                ('tit_rep', models.CharField(db_column='tit_rep', max_length=100)),
                ('desc_rep', models.TextField(blank=True, db_column='desc_rep', null=True)),
                ('fch_rep', models.DateTimeField(auto_now_add=True, db_column='fch_rep')),
                ('id_usu', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, to='accounts.registro')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
    ]
