# Generated by Django 5.2.8 on 2025-11-24 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrativo_cedula_img_administrativo_foto_perfil'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id_email_log', models.AutoField(db_column='id_email_log', primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(db_column='destinatario', max_length=254)),
                ('asunto', models.CharField(db_column='asunto', max_length=150)),
                ('cuerpo_resumen', models.CharField(blank=True, db_column='cuerpo_resumen', max_length=255, null=True)),
                ('exito', models.BooleanField(db_column='exito', default=False)),
                ('error', models.TextField(blank=True, db_column='error', null=True)),
                ('fch_envio', models.DateTimeField(auto_now_add=True, db_column='fch_envio')),
                ('tipo', models.CharField(db_column='tipo', help_text='Ej: password_change, notification', max_length=50)),
                ('id_usu', models.ForeignKey(blank=True, db_column='id_usu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.registro')),
            ],
            options={
                'db_table': 'email_log',
            },
        ),
    ]
