# Generated by Django 5.2.8 on 2025-11-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_inst', models.AutoField(db_column='id_inst', primary_key=True, serialize=False)),
                ('nom_inst', models.CharField(db_column='nom_inst', max_length=100)),
                ('tip_inst', models.CharField(blank=True, db_column='tip_inst', max_length=20, null=True)),
                ('cod_dane_inst', models.CharField(blank=True, db_column='cod_dane_inst', max_length=20, null=True)),
                ('dep_inst', models.CharField(blank=True, db_column='dep_inst', max_length=50, null=True)),
                ('mun_inst', models.CharField(blank=True, db_column='mun_inst', max_length=50, null=True)),
                ('dire_inst', models.CharField(blank=True, db_column='dire_inst', max_length=100, null=True)),
                ('tel_inst', models.CharField(blank=True, db_column='tel_inst', max_length=20, null=True)),
                ('ema_inst', models.CharField(blank=True, db_column='ema_inst', max_length=100, null=True)),
                ('id_adm', models.ForeignKey(db_column='id_adm', on_delete=django.db.models.deletion.PROTECT, to='accounts.administrativo')),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_cur', models.AutoField(db_column='id_cur', primary_key=True, serialize=False)),
                ('grd_cur', models.CharField(db_column='grd_cur', max_length=10)),
                ('num_alum_cur', models.IntegerField(db_column='num_alum_cur', default=0)),
                ('cup_disp_cur', models.IntegerField(db_column='cup_disp_cur', default=0)),
                ('id_inst', models.ForeignKey(db_column='id_inst', on_delete=django.db.models.deletion.CASCADE, to='school.institucion')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_mat', models.AutoField(db_column='id_mat', primary_key=True, serialize=False)),
                ('fch_reg_mat', models.DateField(db_column='fch_reg_mat')),
                ('est_mat', models.CharField(blank=True, db_column='est_mat', max_length=20, null=True)),
                ('obs_mat', models.CharField(blank=True, db_column='obs_mat', max_length=255, null=True)),
                ('id_cur', models.ForeignKey(db_column='id_cur', on_delete=django.db.models.deletion.CASCADE, to='school.curso')),
                ('id_est', models.ForeignKey(db_column='id_est', on_delete=django.db.models.deletion.CASCADE, to='people.estudiante')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_doc', models.AutoField(db_column='id_doc', primary_key=True, serialize=False)),
                ('reg_civil_doc', models.CharField(blank=True, db_column='reg_civil_doc', max_length=100, null=True)),
                ('doc_idn_acu', models.CharField(blank=True, db_column='doc_idn_acu', max_length=100, null=True)),
                ('doc_idn_alum', models.CharField(blank=True, db_column='doc_idn_alum', max_length=100, null=True)),
                ('cnt_vac_doc', models.CharField(blank=True, db_column='cnt_vac_doc', max_length=100, null=True)),
                ('adres_doc', models.CharField(blank=True, db_column='adres_doc', max_length=100, null=True)),
                ('fot_alum_doc', models.CharField(blank=True, db_column='fot_alum_doc', max_length=100, null=True)),
                ('visa_extr_doc', models.CharField(blank=True, db_column='visa_extr_doc', max_length=100, null=True)),
                ('cer_med_disca_doc', models.CharField(blank=True, db_column='cer_med_disca_doc', max_length=100, null=True)),
                ('cer_esc_doc', models.CharField(blank=True, db_column='cer_esc_doc', max_length=100, null=True)),
                ('id_mat', models.ForeignKey(db_column='id_mat', on_delete=django.db.models.deletion.CASCADE, to='school.matricula')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
    ]
