# Generated by Django 5.2.8 on 2025-11-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_acudiente_cedula_img_acudiente_foto_perfil_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='id_est',
            field=models.ForeignKey(blank=True, db_column='id_est', null=True, on_delete=django.db.models.deletion.CASCADE, to='people.estudiante'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id_mat',
            field=models.ForeignKey(blank=True, db_column='id_mat', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.matricula'),
        ),
    ]
