# Generated by Django 5.2.8 on 2025-11-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_acudiente_cedula_img_acudiente_foto_perfil_and_more'),
        ('school', '0002_documento_id_est_alter_documento_id_mat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaRequest',
            fields=[
                ('id_req', models.AutoField(db_column='id_req', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('needs_docs', 'Faltan documentos')], db_column='estado', default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('expires_at', models.DateTimeField(blank=True, db_column='expires_at', null=True)),
                ('obs', models.CharField(blank=True, db_column='obs', max_length=255, null=True)),
                ('id_acu', models.ForeignKey(db_column='id_acu', on_delete=django.db.models.deletion.CASCADE, to='people.acudiente')),
                ('id_cur', models.ForeignKey(db_column='id_cur', on_delete=django.db.models.deletion.CASCADE, to='school.curso')),
                ('id_est', models.ForeignKey(db_column='id_est', on_delete=django.db.models.deletion.CASCADE, to='people.estudiante')),
                ('id_inst', models.ForeignKey(db_column='id_inst', on_delete=django.db.models.deletion.CASCADE, to='school.institucion')),
            ],
            options={
                'db_table': 'matricula_request',
            },
        ),
    ]
