# Generated by Django 5.2.8 on 2025-11-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_matricularequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='grado_solicitado',
            field=models.IntegerField(blank=True, db_column='grado_solicitado', null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_cur',
            field=models.ForeignKey(blank=True, db_column='id_cur', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.curso'),
        ),
    ]
