# Generated by Django 5.2.8 on 2025-11-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_matricula_grado_solicitado_alter_matricula_id_cur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricularequest',
            name='id_cur',
            field=models.ForeignKey(blank=True, db_column='id_cur', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.curso'),
        ),
    ]
