# Generated by Django 5.2.8 on 2025-11-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_matricularequest_id_cur'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricularequest',
            name='grado_solicitado',
            field=models.IntegerField(blank=True, db_column='grado_solicitado', null=True),
        ),
    ]
