# Generated by Django 5.2.8 on 2025-11-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrativo_cedula_img_administrativo_foto_perfil'),
        ('school', '0006_matricularequest_grado_solicitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_not', models.AutoField(db_column='id_not', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=150)),
                ('mensaje', models.TextField(db_column='mensaje')),
                ('leida', models.BooleanField(db_column='leida', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('id_admin', models.ForeignKey(blank=True, db_column='id_adm', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.administrativo')),
                ('id_req', models.ForeignKey(blank=True, db_column='id_req', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.matricularequest')),
            ],
            options={
                'db_table': 'school_notificacion',
            },
        ),
    ]
