# Generated by Django 5.2.8 on 2025-11-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asig', models.AutoField(db_column='id_asig', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nom_asig', max_length=150)),
                ('id_cur', models.ForeignKey(db_column='id_cur', on_delete=django.db.models.deletion.CASCADE, to='school.curso')),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_hor', models.AutoField(db_column='id_hor', primary_key=True, serialize=False)),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')], db_column='dia')),
                ('hora_inicio', models.TimeField(blank=True, db_column='hora_inicio', null=True)),
                ('hora_fin', models.TimeField(blank=True, db_column='hora_fin', null=True)),
                ('aula', models.CharField(blank=True, db_column='aula', max_length=50, null=True)),
                ('id_asig', models.ForeignKey(db_column='id_asig', on_delete=django.db.models.deletion.CASCADE, to='school.asignatura')),
                ('id_cur', models.ForeignKey(db_column='id_cur', on_delete=django.db.models.deletion.CASCADE, to='school.curso')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
    ]
