# Generated by Django 5.2.8 on 2025-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_asignatura_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='id_cur',
        ),
        migrations.AddField(
            model_name='institucion',
            name='allow_duplicate_subject_slots',
            field=models.BooleanField(db_column='allow_dup_sub_slots', default=False),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(db_column='nom_asig', max_length=150, unique=True),
        ),
    ]
