# Generated by Django 5.2.8 on 2025-11-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_maestro'),
        ('school', '0009_remove_asignatura_id_cur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='id_mae',
            field=models.ForeignKey(blank=True, db_column='id_mae', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.maestro'),
        ),
    ]
