# Generated by Django 5.2.8 on 2025-11-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_horario_id_mae'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='img_inst',
            field=models.ImageField(blank=True, db_column='img_inst', null=True, upload_to='instituciones/'),
        ),
    ]
