# Generated by Django 5.2.8 on 2025-11-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrativo_cedula_img_administrativo_foto_perfil'),
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionRequest',
            fields=[
                ('id_req', models.AutoField(primary_key=True, serialize=False)),
                ('nom_inst', models.CharField(max_length=100)),
                ('tip_inst', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_dane_inst', models.CharField(blank=True, max_length=20, null=True)),
                ('dep_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('mun_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('dire_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_inst', models.CharField(blank=True, max_length=20, null=True)),
                ('ema_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('needs_info', 'Falta información')], default='pending', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_adm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.administrativo')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institucion_reviews', to='accounts.registro')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institucion_requests', to='accounts.registro')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
