# Generated by Django 5.2.8 on 2025-11-23 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_institucionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='institucion_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.institucionrequest'),
        ),
    ]
