# Generated by Django 5.2.8 on 2025-11-23 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrativo_cedula_img_administrativo_foto_perfil'),
        ('adminpanel', '0003_adminnotification_institucion_request'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoRequest',
            fields=[
                ('id_req', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(default='primaria', max_length=20)),
                ('sections', models.IntegerField(default=3)),
                ('cupos', models.IntegerField(default=30)),
                ('start_grade', models.IntegerField(blank=True, null=True)),
                ('end_grade', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('needs_info', 'Falta información')], default='pending', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_inst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.institucion')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso_reviews', to='accounts.registro')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso_requests', to='accounts.registro')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
