# Generated by Django 5.2.8 on 2025-11-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_cursorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='curso_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.cursorequest'),
        ),
    ]
