# Generated by Django 5.2.8 on 2025-11-23 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_adminnotification_curso_request'),
        ('school', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='matricula_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.matricularequest'),
        ),
    ]
