# Generated by Django 5.2.8 on 2025-11-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_usu', models.AutoField(db_column='id_usu', primary_key=True, serialize=False)),
                ('nom_usu', models.CharField(db_column='nom_usu', max_length=50)),
                ('ape_usu', models.CharField(db_column='ape_usu', max_length=50)),
                ('ema_usu', models.EmailField(db_column='ema_usu', max_length=100, unique=True)),
                ('con_usu', models.CharField(db_column='con_usu', max_length=255)),
            ],
            options={
                'db_table': 'registro',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(db_column='nom_rol', max_length=50)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_adm', models.AutoField(db_column='id_adm', primary_key=True, serialize=False)),
                ('num_doc_adm', models.CharField(db_column='num_doc_adm', max_length=20)),
                ('tel_adm', models.CharField(blank=True, db_column='tel_adm', max_length=20, null=True)),
                ('dir_adm', models.CharField(blank=True, db_column='dir_adm', max_length=100, null=True)),
                ('tip_carg_adm', models.CharField(blank=True, db_column='tip_carg_adm', max_length=50, null=True)),
                ('id_usu', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, to='accounts.registro')),
            ],
            options={
                'db_table': 'administrativo',
            },
        ),
        migrations.AddField(
            model_name='registro',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='accounts.rol'),
        ),
    ]
