# Generated by Django 5.2.8 on 2025-11-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_insert_initial_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='cedula_img',
            field=models.ImageField(blank=True, db_column='cedula_img', null=True, upload_to='administrativos/cedulas/'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='foto_perfil',
            field=models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='administrativos/fotos/'),
        ),
    ]
