# Generated by Django 5.2.8 on 2025-11-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrativo_cedula_img_administrativo_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.AutoField(db_column='id_pwd_req', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('used', models.BooleanField(db_column='used', default=False)),
                ('ip_request', models.CharField(blank=True, db_column='ip_request', max_length=45, null=True)),
                ('registro', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='accounts.registro')),
            ],
            options={
                'db_table': 'password_reset_request',
            },
        ),
    ]
