# Generated by Django 5.2.8 on 2025-12-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='dir_adm',
            field=models.CharField(blank=True, db_column='dir_adm', max_length=300, null=True),
        ),
    ]
