# Generated by Django 5.2.8 on 2025-11-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_acu', models.AutoField(db_column='id_acu', primary_key=True, serialize=False)),
                ('num_doc_acu', models.CharField(db_column='num_doc_acu', max_length=20)),
                ('tel_acu', models.CharField(blank=True, db_column='tel_acu', max_length=20, null=True)),
                ('dir_acu', models.CharField(blank=True, db_column='dir_acu', max_length=100, null=True)),
                ('id_usu', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, to='accounts.registro')),
            ],
            options={
                'db_table': 'acudiente',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_est', models.AutoField(db_column='id_est', primary_key=True, serialize=False)),
                ('tip_doc_est', models.CharField(blank=True, db_column='tip_doc_est', max_length=20, null=True)),
                ('num_doc_est', models.CharField(db_column='num_doc_est', max_length=20)),
                ('fch_nac_estu', models.DateField(blank=True, db_column='fch_nac_estu', null=True)),
                ('tel_estu', models.CharField(blank=True, db_column='tel_estu', max_length=20, null=True)),
                ('id_acu', models.ForeignKey(db_column='id_acu', on_delete=django.db.models.deletion.CASCADE, to='people.acudiente')),
                ('id_usu', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, to='accounts.registro')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
    ]
