# Generated by Django 5.2.8 on 2025-11-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='cedula_img',
            field=models.ImageField(blank=True, db_column='cedula_img', null=True, upload_to='acudientes/cedulas/'),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='foto_perfil',
            field=models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='acudientes/fotos/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil',
            field=models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='estudiantes/fotos/'),
        ),
    ]
