# Generated by Django 5.2.8 on 2025-11-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrativo_cedula_img_administrativo_foto_perfil'),
        ('people', '0002_acudiente_cedula_img_acudiente_foto_perfil_and_more'),
        ('school', '0009_remove_asignatura_id_cur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id_mae', models.AutoField(db_column='id_mae', primary_key=True, serialize=False)),
                ('num_doc_mae', models.CharField(db_column='num_doc_mae', max_length=20)),
                ('tel_mae', models.CharField(blank=True, db_column='tel_mae', max_length=20, null=True)),
                ('dir_mae', models.CharField(blank=True, db_column='dir_mae', max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, db_column='especialidad', max_length=100, null=True)),
                ('foto_perfil', models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='maestros/fotos/')),
                ('id_inst', models.ForeignKey(blank=True, db_column='id_inst', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.institucion')),
                ('id_usu', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, to='accounts.registro')),
            ],
            options={
                'db_table': 'maestro',
            },
        ),
    ]
