# Generated by Django 5.2.8 on 2025-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_acudiente_geo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='dir_acu',
            field=models.CharField(blank=True, db_column='dir_acu', max_length=200, null=True),
        ),
    ]
