# Generated by Django 5.2.8 on 2025-12-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_acudiente_dir_acu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='dir_acu',
            field=models.CharField(blank=True, db_column='dir_acu', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='dir_mae',
            field=models.CharField(blank=True, db_column='dir_mae', max_length=300, null=True),
        ),
    ]
